{{- if .Values.frontend.enabled }}
# frontend : application Angular servie par nginx.
# On utilise un ROLLOUT (Argo Rollouts) au lieu d'un Deployment classique
# => déploiement CANARY : la nouvelle version monte progressivement 20→40→60→100 %.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
  # ============ LA STRATÉGIE CANARY ============
  strategy:
    canary:
      steps:
        - setWeight: 20          # 20 % du trafic vers la v2
        - pause: {duration: 30s} # on observe 30 s
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {}              # ⏸️ PAUSE INFINIE = validation manuelle (tu décides)
        - setWeight: 100         # promotion finale
{{- end }}
